# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('menu', models.CharField(max_length=20)),
                ('price', models.IntegerField(verbose_name='가격')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(choices=[('아주 좋아요', '5'), ('좋아요', '4'), ('보통이에요', '3'), ('별로에요', '2'), ('최악!', '1')], max_length=20)),
            ],
        ),
    ]
