# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.IntegerField(choices=[(5, '아주 좋아요'), (4, '좋아요'), (3, '보통이에요'), (2, '별로에요'), (1, '최악!')]),
        ),
    ]
