# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_shop_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='photo',
            field=models.ImageField(blank=True, upload_to='shop'),
        ),
    ]
